spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sdysjdsr1225*
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
#    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    request-context-attribute: request
    suffix: .ftl
server:
  port: 8082
  servlet:
    context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/xuda/Downloads/sell.log
#  level:
#    com.qxholy.selltest.LoggerTest: debug

wechat:
  mpAppId: wxebfd78fa1898d74b
  mpAppSecret: 010c2d97fb1fb0433039024c499b497e
  mchId: 1541092771
  mchKey: SDysjdsr1225SDysjdsr1225SDysjdsr
  keyPath: /Users/xuda/cert/xd.p12
  notifyUrl: https://www.qxholy.com/sell/pay/notify